// constants/mastercv-fields.ts
import { TransaksiCv, PemilikManfaatCv, Prisma } from '.prisma/main-client';

export const masterCvAllowedFields: (any)[] = [
  'id_notaris',
  'id_pengajuan_nama_cv',
  'no_transaksi',
  'no_surat',
  'no_telpon',
  'email',
  'jangka_waktu',
  'batas_waktu',
  'id_provinsi',
  'id_kabupaten',
  'id_kecamatan',
  'id_kelurahan',
  'alamat',
  'rt',
  'rw',
  'kode_pos',
  'npwp',
  'no_akta',
  'tgl_akta',
  'id_notaris_pengganti',
  'jumlah_aset',
  'created_by',
];

export const masterFirmaAllowedFields: (any)[] = [
  'id_notaris',
  'id_pengajuan_nama_firma',
  'no_transaksi',
  'no_surat',
  'no_telpon',
  'email',
  'jangka_waktu',
  'batas_waktu',
  'id_provinsi',
  'id_kabupaten',
  'id_kecamatan',
  'id_kelurahan',
  'alamat',
  'rt',
  'rw',
  'kode_pos',
  'npwp',
  'no_akta',
  'tgl_akta',
  'id_notaris_pengganti',
  'jumlah_aset',
  'created_by',
];

export const masterPerdataAllowedFields: (any)[] = [
  'id_notaris',
  'id_pengajuan_nama_perdata',
  'no_transaksi',
  'no_surat',
  'no_telpon',
  'email',
  'jangka_waktu',
  'batas_waktu',
  'id_provinsi',
  'id_kabupaten',
  'id_kecamatan',
  'id_kelurahan',
  'alamat',
  'rt',
  'rw',
  'kode_pos',
  'npwp',
  'no_akta',
  'tgl_akta',
  'id_notaris_pengganti',
  'jumlah_aset',
  'created_by',
];

